### ISSUE TITLE
copying default object translation as an annotation option 

### ISSUE THREAD

**Issue by JarekW** [fsi-open/doctrine-extensions#62]
... that is set per field 

```
@Translatable\Translatable(mappedBy="translations", copyFromDefault=true)
```

This is useful when working with translatable collections. When collection is translatable you must have at least one element in collection to not show elements from default translation element. There's no way to have nothing in specific language when default translation have some elements.

i'm aware that this might introduce some complications with something that depend on default translations

**Comment by szymach** [comment]
I am not sure this will fix the problem. During data display this will not be all that useful (since you should restrict data at the fetching stage to the current language only), and during edition it may result in a mix of fields having and not having values from the default locale.

Ideally we would want some mechanism turning the overriding with default locale values on and off per object. Not sure how though.

**Comment by szymach** [comment]
This is a rather extreme use case and not worth the effort to implement.
